# Generated by Django 5.2.4 on 2025-08-04 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Layanan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_layanan", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="RekomendasiTeknis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_usulan", models.CharField(max_length=255)),
                ("tujuan", models.CharField(max_length=255)),
                ("deskripsi", models.TextField()),
                ("lokasi", models.CharField(max_length=255)),
                ("jumlah_usulan", models.CharField(max_length=255)),
                ("nama_pemohon", models.CharField(max_length=255)),
                ("kontak_pemohon", models.CharField(max_length=100)),
                ("email_pemohon", models.EmailField(max_length=254)),
                (
                    "foto_lokasi",
                    models.ImageField(blank=True, null=True, upload_to="foto_lokasi/"),
                ),
                (
                    "koordinat_longitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                (
                    "koordinat_latitude",
                    models.DecimalField(decimal_places=6, max_digits=9),
                ),
                ("tanggal_permohonan", models.DateField(auto_now_add=True)),
                (
                    "layanan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="rekomtek.layanan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StatusRekomendasiTeknis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jadwal_kunjungan_lapangan", models.DateField(blank=True, null=True)),
                (
                    "tanggal_kunjungan_lapangan_1",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "tanggal_kunjungan_lapangan_2",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "rekomtek",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_rekomtek",
                        to="rekomtek.rekomendasiteknis",
                    ),
                ),
            ],
        ),
    ]
