# Generated by Django 5.2.4 on 2025-08-07 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rekomtek", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="layanan",
            options={"verbose_name_plural": "1. Layanan"},
        ),
        migrations.AlterModelOptions(
            name="rekomendasiteknis",
            options={"verbose_name_plural": "2. Rekomendasi Teknis"},
        ),
        migrations.AlterModelOptions(
            name="statusrekomendasiteknis",
            options={"verbose_name_plural": "3. Status Rekomendasi Teknis"},
        ),
    ]
