# Generated by Django 5.2.4 on 2025-07-29 00:21

import ckeditor.fields
import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="KategoriInfrastrukturSda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_kategori", models.CharField(max_length=255)),
                ("tgl_buat", models.DateField(auto_now_add=True)),
                ("tgl_update", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "1. Kategori",
                "db_table": "kategori_infrastruktur_sda",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("content", ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name="InfrastrukturSda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                (
                    "gambar",
                    models.ImageField(
                        blank=True, null=True, upload_to="Pembangunan_sda"
                    ),
                ),
                (
                    "uraian",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "data_teknis",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, null=True
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=225, null=True, unique=True
                    ),
                ),
                ("tgl_buat", models.DateField(auto_now_add=True)),
                ("tgl_update", models.DateField(auto_now_add=True)),
                (
                    "kategori",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="infrastruktur_sda.kategoriinfrastruktursda",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "2. Infrastruktur Sda",
                "db_table": "infrastruktur_sda",
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="PekerjaanSda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_pekerjaan", models.CharField(max_length=150)),
                ("tahun", models.CharField(max_length=150)),
                (
                    "pagu_anggaran",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "sumber_dana",
                    models.CharField(blank=True, max_length=150, null=True),
                ),
                ("kontraktor", models.CharField(blank=True, max_length=150, null=True)),
                ("konsultan", models.CharField(blank=True, max_length=150, null=True)),
                ("tgl_buat", models.DateField(auto_now_add=True)),
                ("tgl_update", models.DateField(auto_now_add=True)),
                (
                    "infrastruktur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pekerjaan_set",
                        to="infrastruktur_sda.infrastruktursda",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "3. Pekerjaan Sda",
                "db_table": "pekerjaan_sda",
                "managed": True,
            },
        ),
    ]
