# Generated by Django 5.2.4 on 2025-07-31 06:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PesanKontak",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subjek", models.CharField(max_length=150)),
                ("pesan", models.TextField()),
                ("tanggal_kirim", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
