# Generated by Django 5.2.4 on 2025-07-31 07:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contact", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pesankontak",
            name="tanggal_kirim",
            field=models.DateField(auto_now_add=True),
        ),
    ]
