# Generated by Django 5.2.4 on 2025-07-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("berita", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="artikel",
            options={"verbose_name_plural": "Artikel"},
        ),
        migrations.AlterField(
            model_name="artikel",
            name="thumbnail",
            field=models.ImageField(blank=True, null=True, upload_to="artikel"),
        ),
    ]
