# Generated by Django 5.2.4 on 2025-07-17 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("berita", "0002_alter_artikel_options_alter_artikel_thumbnail"),
    ]

    operations = [
        migrations.CreateModel(
            name="Kategori",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "1. Kategori",
            },
        ),
        migrations.AlterModelOptions(
            name="artikel",
            options={"verbose_name_plural": "2. Artikel"},
        ),
        migrations.AddField(
            model_name="artikel",
            name="kategori",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="berita.kategori",
            ),
        ),
    ]
