# Generated by Django 5.2.4 on 2025-07-19 14:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("berita", "0003_kategori_alter_artikel_options_artikel_kategori"),
    ]

    operations = [
        migrations.AddField(
            model_name="artikel",
            name="tgl_buat",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="artikel",
            name="tgl_update",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
