# Generated by Django 5.2.4 on 2025-07-20 03:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("berita", "0004_artikel_tgl_buat_artikel_tgl_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artikel",
            name="tgl_buat",
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="artikel",
            name="tgl_update",
            field=models.DateField(auto_now_add=True),
        ),
    ]
