# Generated by Django 5.2.4 on 2025-07-20 04:24

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("berita", "0005_alter_artikel_tgl_buat_alter_artikel_tgl_update"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artikel",
            name="isi",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
