# Generated by Django 5.2.4 on 2025-08-03 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("berita", "0006_alter_artikel_isi"),
    ]

    operations = [
        migrations.AddField(
            model_name="artikel",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
