# Generated by Django 5.2.4 on 2025-08-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("berita", "0007_artikel_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="artikel",
            name="slug",
            field=models.SlugField(blank=True, max_length=225, null=True, unique=True),
        ),
    ]
