# Generated by Django 5.2.4 on 2025-07-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Foto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama_kegiatan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uraian_singkat",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Foto_dokumentasi",
                    models.ImageField(blank=True, null=True, upload_to=""),
                ),
                ("tanggal_kegiatan", models.DateField()),
                ("tanggal_upload", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "1. Foto",
            },
        ),
    ]
