# Generated by Django 5.2.4 on 2025-07-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeri", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foto",
            name="Foto_dokumentasi",
            field=models.ImageField(blank=True, null=True, upload_to="foto"),
        ),
    ]
