# Generated by Django 5.2.4 on 2025-07-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeri", "0002_alter_foto_foto_dokumentasi"),
    ]

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judul_video",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uraian_singkat",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file_video", models.FileField(upload_to="video/")),
                ("tanggal_kegiatan", models.DateField()),
                ("tanggal_upload", models.DateField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "2. Video",
            },
        ),
    ]
