# Generated by Django 5.2.4 on 2025-07-29 05:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeri", "0003_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foto",
            name="tanggal_kegiatan",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="tanggal_kegiatan",
            field=models.DateTimeField(),
        ),
    ]
