# Generated by Django 5.2.4 on 2025-07-29 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeri", "0004_alter_foto_tanggal_kegiatan_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="foto",
            name="tanggal_kegiatan",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="video",
            name="tanggal_kegiatan",
            field=models.DateField(),
        ),
    ]
