# Generated by Django 5.2.4 on 2025-08-03 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeri", "0005_alter_foto_tanggal_kegiatan_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="foto",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="video",
            name="views",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
