# Generated by Django 5.2.4 on 2025-08-06 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeri", "0006_foto_views_video_views"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_album", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="foto",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="foto_album",
                to="galeri.album",
            ),
        ),
    ]
