# Generated by Django 5.2.4 on 2025-08-06 01:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("galeri", "0007_album_foto_album"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="foto",
            name="album",
        ),
        migrations.DeleteModel(
            name="Album",
        ),
    ]
