# Generated by Django 5.2.4 on 2025-08-06 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeri", "0008_remove_foto_album_delete_album"),
    ]

    operations = [
        migrations.CreateModel(
            name="FotoKegiatanPerencanaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nama_kegiatan",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uraian_singkat",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "Foto_dokumentasi",
                    models.ImageField(blank=True, null=True, upload_to="foto"),
                ),
                ("tanggal_kegiatan", models.DateField()),
                ("tanggal_upload", models.DateField(auto_now_add=True)),
                ("views", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "2. Foto Kegiatan Perencanaan",
            },
        ),
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name_plural": "3. Video"},
        ),
    ]
