# Generated by Django 5.2.4 on 2025-08-06 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeri", "0009_fotokegiatanperencanaan_alter_video_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="KategoriKegiatanFisik",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_kategori", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Kategori Kegiatan Fisik",
            },
        ),
        migrations.CreateModel(
            name="KategoriKegiatanPerencanaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_kategori", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Kategori Kegiatan Perencanaan",
            },
        ),
        migrations.AddField(
            model_name="foto",
            name="kategori",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="galeri.kategorikegiatanfisik",
            ),
        ),
        migrations.AddField(
            model_name="fotokegiatanperencanaan",
            name="kategori",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="galeri.kategorikegiatanperencanaan",
            ),
        ),
    ]
