# Generated by Django 5.2.4 on 2025-08-06 05:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("galeri", "0010_kategorikegiatanfisik_kategorikegiatanperencanaan_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="foto",
            options={"verbose_name_plural": "3. Foto Kegiatan Fisik"},
        ),
        migrations.AlterModelOptions(
            name="fotokegiatanperencanaan",
            options={"verbose_name_plural": "4. Foto Kegiatan Perencanaan"},
        ),
        migrations.AlterModelOptions(
            name="kategorikegiatanfisik",
            options={"verbose_name_plural": "1. Kategori Kegiatan Fisik"},
        ),
        migrations.AlterModelOptions(
            name="kategorikegiatanperencanaan",
            options={"verbose_name_plural": "2. Kategori Kegiatan Perencanaan"},
        ),
    ]
