# Generated by Django 5.2.4 on 2025-08-07 01:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("galeri", "0011_alter_foto_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name_plural": "5. Video"},
        ),
    ]
