# Generated by Django 5.2.4 on 2025-08-07 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("galeri", "0012_alter_video_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoKegiatanPerencanaan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "judul_video",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "uraian_singkat",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("file_video", models.FileField(upload_to="video/")),
                ("tanggal_kegiatan", models.DateField()),
                ("tanggal_upload", models.DateField(auto_now_add=True)),
                ("views", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "5. Video Kegiatan Perencanaan",
            },
        ),
        migrations.AlterModelOptions(
            name="video",
            options={"verbose_name_plural": "5. Video Kegiatan Fisik"},
        ),
    ]
