# Generated by Django 5.2.4 on 2025-07-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LokasiKantor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama_kantor", models.CharField(max_length=255)),
                ("alamat", models.TextField()),
                ("telepon", models.CharField(blank=True, max_length=20, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "koordinat_lat",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "koordinat_long",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("tgl_dibuat", models.DateTimeField(auto_now_add=True)),
                ("tgl_diperbarui", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sejarah",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isi", models.TextField()),
                ("tgl_dibuat", models.DateTimeField(auto_now_add=True)),
                ("tgl_diperbarui", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="StrukturOrganisasi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nama", models.CharField(max_length=255)),
                ("jabatan", models.CharField(max_length=255)),
                ("foto", models.ImageField(upload_to="struktur/")),
                ("urutan", models.PositiveIntegerField(default=0)),
                ("tgl_dibuat", models.DateTimeField(auto_now_add=True)),
                ("tgl_diperbarui", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["urutan"],
            },
        ),
        migrations.CreateModel(
            name="TugasFungsi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("isi", models.TextField()),
                ("tgl_dibuat", models.DateTimeField(auto_now_add=True)),
                ("tgl_diperbarui", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="VisiMisi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("visi", models.TextField()),
                ("misi", models.TextField()),
                ("tgl_dibuat", models.DateTimeField(auto_now_add=True)),
                ("tgl_diperbarui", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
