# Generated by Django 5.2.4 on 2025-07-19 06:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profil", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="lokasikantor",
            options={"verbose_name_plural": "5. Lokasi Kantor"},
        ),
        migrations.AlterModelOptions(
            name="sejarah",
            options={"verbose_name_plural": "4. Sejarah"},
        ),
        migrations.AlterModelOptions(
            name="strukturorganisasi",
            options={
                "ordering": ["urutan"],
                "verbose_name_plural": "3. Struktur Organisasi",
            },
        ),
        migrations.AlterModelOptions(
            name="tugasfungsi",
            options={"verbose_name_plural": "2. Tugas Fungsi"},
        ),
        migrations.AlterModelOptions(
            name="visimisi",
            options={"verbose_name_plural": "1. Visi dan Misi"},
        ),
        migrations.RemoveField(
            model_name="tugasfungsi",
            name="isi",
        ),
        migrations.AddField(
            model_name="tugasfungsi",
            name="fungsi",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="tugasfungsi",
            name="tugas",
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="visimisi",
            name="misi",
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name="visimisi",
            name="visi",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
