# Generated by Django 5.2.4 on 2025-07-19 06:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profil", "0002_alter_lokasikantor_options_alter_sejarah_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tugasfungsi",
            name="fungsi",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="tugasfungsi",
            name="tugas",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
