# Generated by Django 5.2.4 on 2025-07-19 14:43

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("profil", "0003_alter_tugasfungsi_fungsi_alter_tugasfungsi_tugas"),
    ]

    operations = [
        migrations.AlterField(
            model_name="visimisi",
            name="misi",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
        migrations.AlterField(
            model_name="visimisi",
            name="visi",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                blank=True, null=True
            ),
        ),
    ]
