# Generated by Django 5.2.4 on 2025-07-21 01:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("kelembagaan", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="tkpsda",
            options={"verbose_name_plural": "1. TKPSDA"},
        ),
    ]
